version: "3.1"

volumes:
  postgres:
  minio:
  certstore:

services:

  traefik:
    image: "traefik:latest"
    command:
      - "--providers.docker"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesResolvers.le.acme.email=contact@zekro.de"
      - "--certificatesResolvers.le.acme.storage=/etc/certstore/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=http"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/config:/etc/traefik/dynamic_conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/cert:/etc/cert:ro"
      - "certstore:/etc/certstore"

  postgres:
    image: "postgres:latest"
    expose:
      - "5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    restart: always

  redis:
    image: "redis:latest"
    expose:
      - "6379"
    restart: always

  vctr-gw:
    image: "zekro/vctr-gw:latest"
    expose:
      - "80"
    environment:
      VCTR_CONNECTIONSTRINGS__POSTGRES: "Host=postgres;Database=vctr;Username=root;Password=root"
      VCTR_INITIALIZATION__ROOTUSERNAME: "root"
      VCTR_INITIALIZATION__ROOTUSERPASSWORD: "root"
      VCTR_CACHING__DURATION: "30.00:00:00"
      VCTR_CACHING__REDIS__SERVERS: "redis:6379"
      VCTR_CACHING__REDIS__DATABASE: 0
      VCTR_ROUTING__NOTFOUND: "/ui/notfound"
      VCTR_ROUTING__PASSWORD: "/ui/password"
    restart: always
    depends_on:
      - "minio"
      - "redis"
      - "postgres"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vctr-gw.entrypoints=https"
      - "traefik.http.routers.vctr-gw.tls=true"
      - "traefik.http.routers.vctr-gw.tls.certresolver=le"
      - "traefik.http.routers.vctr-gw.rule=Host(`demo.zekro.de`)"

  vctr-fe:
    image: "zekro/vctr-fe:latest"
    expose:
      - "80"
    restart: always
    depends_on:
      - "vctr-gw"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vctr-fe.entrypoints=https"
      - "traefik.http.routers.vctr-fe.tls=true"
      - "traefik.http.routers.vctr-fe.tls.certresolver=le"
      - "traefik.http.routers.vctr-fe.rule=Host(`demo.zekro.de`) && PathPrefix(`/ui`)"
      - "traefik.http.routers.vctr-fe.middlewares=vctr-fe-stripprefix"
      - "traefik.http.middlewares.vctr-fe-stripprefix.stripprefix.prefixes=/ui/"